name: A침adir nuevo tenant

on: 
    workflow_dispatch:
        inputs:
            tenantName:
                description: 'Nombre del nuevo tenant'
                required: true
                default: ''
            tenantId:
                description: 'Id del nuevo tenant'
                required: true
                default: ''

jobs:
  nuevoTenant:
    runs-on: windows-latest
        
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{secrets.ghTokenWorkflow}}
          fetch-depth: 0
      - name: a침adir Tenant
        run: |
          $tenantName = '${{github.event.inputs.tenantName}}'
          $tenantId = '${{github.event.inputs.tenantId}}'
          if (-not ($tenantID -match '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$')){
              Write-Error "El tenantId no es un GUID v치lido"
              exit 1
          }
          $data = Get-Content ./.github/metadata/tenants.json | ConvertFrom-Json
            $data = @($data)
          $data += [PSCustomObject]@{
              name = $tenantName
              tenantID = $tenantId
          }
          $data | ConvertTo-Json | Set-Content ./.github/metadata/tenants.json -Force -Encoding UTF8

      - name: Commit changes
        run: |
          git config --global user.name "${{github.actor}}[bot]"
          git config --global user.email "${{github.actor}}[bot]@users.noreply.github.com"
          git add .
          git commit -m "A침adido nuevo tenant $tenantName"
          git push