name: Crear entornos por cada cliente que tenga esta app

on: 
    workflow_dispatch:

jobs:
    crearEntorno:
        runs-on: windows-latest
        name: Crear Entorno

        steps:
            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                ref: ${{ matrix.branch }}
                token: ${{secrets.ghTokenWorkflow}}
            
            - name: Crear Entornos
              shell: powershell
              run:
                Write-Host "Antes de Entrar"
                helloWorld
                .github/scripts/crearEntornosPorCliente.ps1 -repoPath $env:REPOPATH
                Write-Host "Tras Entrar"
              env:
                REPOPATH: ${{github.repository}}