name: Crear entornos por cada cliente que tenga esta app

on: 
    workflow_dispatch:

jobs:
    crearEntorno:
      runs-on: windows-latest
      name: Crear Entorno
      env:
        OWNER: ${{github.repository_owner}}
        GH_TOKEN: ${{secrets.ghTokenWorkflow}}
      
      steps:
        - name: Checkout
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
          with:
            token: ${{secrets.ghTokenWorkflow}}
        
        - name: Crear Entornos
          shell: powershell
          run: .github/scripts/crearEntornosPorCliente.ps1 -repoPath $env:REPOPATH
          env:
            REPOPATH: ${{github.repository}}