name: Crear entornos por cada cliente que tenga esta app

on: 
    workflow_dispatch:

jobs:
    crearEntorno:
      runs-on: windows-latest
      name: Crear Entorno  
      
      steps:
        - name: Checkout
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
          with:
            ref: ${{ matrix.branch }}
            token: ${{secrets.ghTokenWorkflow}}
        
        - name: Verificar existencia del script
          shell: powershell
          run: |
            if (Test-Path ".github/scripts/crearEntornosPorCliente.ps1") {
              Write-Host "Script encontrado"
            } else {
              Write-Host "Script NO encontrado"
            }

        - name: Crear Entornos
          shell: powershell
          run: |
            Write-Host "Antes de Entrar"
            .github/scripts/crearEntornosPorCliente.ps1 -repoPath $env:REPOPATH
            Write-Host "Tras Entrar"
          env:
            REPOPATH: ${{github.repository}}