name: Eliminar tenant

on: 
    workflow_dispatch:
        inputs:
            tenantId:
                description: 'Id del tenant a eliminar'
                required: true
                default: ''

jobs:
  eliminarTenant:
    runs-on: windows-latest
        
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{secrets.ghTokenWorkflow}}
          fetch-depth: 0
      - name: eliminar Tenant
        run: |
          $tenantId = '${{github.event.inputs.tenantId}}'
          if (-not ($tenantID -match '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$')){
              Write-Error "El tenantId no es un GUID válido"
              exit 1
          }
          $data = Get-Content ./.github/metadata/tenants.json | ConvertFrom-Json
          $data = $data | Where-Object { $_.tenantID -ne $tenantId }
          $data | ConvertTo-Json | Set-Content ./.github/metadata/tenants.json -Force -Encoding UTF8

      - name: Commit changes
        run: |
          git config --global user.name "${{github.actor}}[bot]"
          git config --global user.email "${{github.actor}}[bot]@users.noreply.github.com"
          git add .
          git commit -m "Eliminado tenant $tenantId"
          git push