name: GH Token rotation

on: 
  workflow_dispatch:
  #schedule:
  #  - cron: '0 1 * * 1' # Se ejecuta cada lunes a la 1:00 AM UTC es decir, 3:00 AM en verano y 2:00 AM en invierno (MIN (0-59), HORA (0-23), DIA DEL MES (1-31), MES (1-12), DIA DE LA SEMANA(0-6, siendo 0 el domingo y 6 el sábado))

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
   
  rotate-secret:
    runs-on: windows-latest
    name: Rotate Secret
    outputs:
      deploymentEnvironmentsJson: ${{ steps.DetermineDeploymentEnvironments.outputs.DeploymentEnvironmentsJson }}
      ghTokenWorkflow: ${{steps.ReadSecrets.outputs.Secrets}}
    env:
      VAULTNAME: 'KeyVaultInv'
      ORG: ${{github.repository_owner}}
      GITHUB_TOKEN: ${{secrets.ghTokenWorkflow}}

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ matrix.branch }}
          token: ${{ secrets.ghTokenWorkflow }}
      
      - name: Read settings
        uses: microsoft/AL-Go-Actions/ReadSettings@v7.2
        with:
          shell: ${{ matrix.shell }}
          get: type,powerPlatformSolutionFolder
      
      - name: EnvName
        id: envName
        run: |
          $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
          $envName = '${{ matrix.environment }}'.split(' ')[0]
          Add-Content -Encoding UTF8 -Path $env:GITHUB_OUTPUT -Value "envName=$envName"
      
      - name: Read secrets
        id: ReadSecrets
        uses: microsoft/AL-Go-Actions/ReadSecrets@v7.2
        with:
          shell: ${{ matrix.shell }}
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: '${{ steps.envName.outputs.envName }}-AuthContext,${{ steps.envName.outputs.envName }}_AuthContext,AuthContext'
      
      - name: Determine Deployment Environments
        id: DetermineDeploymentEnvironments
        uses: microsoft/AL-Go-Actions/DetermineDeploymentEnvironments@v7.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          shell: powershell
          getEnvironments: '*'
          type: 'CD'
      
      - name: Iniciar sesion en azure 
        shell: powershell
        run: az login --use-device-code
      
      - name: Comprobar fecha y actualizar el token del workflow
        shell: powershell
        run: | 
          Write-Host '-------------------vault inv:' $env:VAULTNAME
          .github/scripts/ghtokenrotation.ps1 -keyvaultname $env:VAULTNAME -matchPattern '^gh-wkt-pool-\d{3}$' -action 'Workflow' -metadataPath './github/metadata/workflow-secrets-metadata.json' -organization $env:ORG

      - name: Comprobar fecha y actualizar secret del delivery a StorageAccount
        shell: powershell
        run: .github/scripts/ghtokenrotation.ps1 -keyvaultname $env:VAULTNAME -matchPattern '^gh-repo-pool-\d{3}$' -action 'StorageAccountDelivery' -metadataPath './github/metadata/SA-secrets-metadata.json'

      - name: Comprobar fecha y actualizar secret del delivery a github gitHubPackages
        shell: powershell
        run: .github/scripts/ghtokenrotation.ps1 -keyvaultname $env:VAULTNAME -matchPattern '^gh-ghp-pool-\d{3}$' -action 'ghPackagesDeliver' -metadataPath './github/metadata/GHP-secrets-metadata.json' -organization $env:ORG

      - name: Comprobar fecha y actualizar secrets de entorno (clientes)
        shell: powershell
        run: .github/scripts/ghtokenrotation.ps1 -keyvaultname $env:VAULTNAME -matchPattern '^[cC]lient.*-AUTHCONTEXT-pool-\d{3}$' -action 'environment' -metadataPath './github/metadata/client-secrets-metadata.json'
        env:
          ENVJSON: ${{steps.DetermineDeploymentEnvironments.outputs.DeploymentEnvironmentsJson}}