name: GH Token rotation

on: 
  workflow_dispatch:
  #schedule:
  #  - cron: '0 1 * * 1' # Se ejecuta cada lunes a la 1:00 AM UTC es decir, 3:00 AM en verano y 2:00 AM en invierno (MIN (0-59), HORA (0-23), DIA DEL MES (1-31), MES (1-12), DIA DE LA SEMANA(0-6, siendo 0 el domingo y 6 el s치bado))

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
   
  rotate-secret:
    runs-on: windows-latest
    name: Rotate Secret
    outputs:
      deploymentEnvironmentsJson: ${{ steps.DetermineDeploymentEnvironments.outputs.DeploymentEnvironmentsJson }}
      ghTokenWorkflow: ${{steps.ReadSecrets.outputs.Secrets}}

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ matrix.branch }}
          token: ${{ secrets.ghTokenWorkflow }}
      
      - name: Read settings
        uses: microsoft/AL-Go-Actions/ReadSettings@v7.2
        with:
          shell: ${{ matrix.shell }}
          get: type,powerPlatformSolutionFolder
      
      - name: EnvName
        id: envName
        run: |
          $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
          $envName = '${{ matrix.environment }}'.split(' ')[0]
          Add-Content -Encoding UTF8 -Path $env:GITHUB_OUTPUT -Value "envName=$envName"
      
      - name: Read secrets
        id: ReadSecrets
        uses: microsoft/AL-Go-Actions/ReadSecrets@v7.2
        with:
          shell: ${{ matrix.shell }}
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: '${{ steps.envName.outputs.envName }}-AuthContext,${{ steps.envName.outputs.envName }}_AuthContext,AuthContext'
      
      - name: Determine Deployment Environments
        id: DetermineDeploymentEnvironments
        uses: microsoft/AL-Go-Actions/DetermineDeploymentEnvironments@v7.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          shell: powershell
          getEnvironments: '*'
          type: 'CD'
      
      # - name: debug
      #   run: |
      #     $count=0
      #     $environments = ConvertFrom-Json $env:ENVJSON
      #     foreach($env in $environments){
      #       foreach($key in $env.PSObject.Properties.Name){
      #         $obj = $env.$key
      #         $envName= $obj.EnvironmentName
      #         $count += 1
      #         Write-Host '-------------------count:' $count
      #         Write-Host '------------------------------name:' $envName
      #         $secret = gh secret list -e $envName --json name,updatedAt | ConvertFrom-Json
      #         $secretName = $secret.name
      #         if ($envName -like 'test'){
      #           $pswd = "contrase침a de prueba"
      #           Write-Host '-----------entorno:'
      #           gh secret set $env:SECRETTEST --env $envName --body $pswd
      #           Write-Host '-----------repositorio:'
      #           gh secret set $env:SECRETTEST -b $pswd
      #           Write-Host '------------organizaci칩n:'
      #           gh secret set $env:SecretName -o 'investigacionPrac'
      #           Write-Host '------ secreto cambiado correctamente a:' $pswd
      #           Write-Host '-------------------SecretName en el yaml:' $secretName            
      #         }
      #       }
      #     }
      #   env:
      #     ENVJSON: ${{steps.DetermineDeploymentEnvironments.outputs.DeploymentEnvironmentsJson}}
      #     GITHUB_TOKEN: ${{secrets.ghTokenWorkflow}}

      - name: Comprobar fecha y actualizar secrets de repositorio
        shell: powershell
        run: .github/scripts/ghtokenrotation.ps1 -keyvaultname $vaultName -matchPattern '^gh-repo-pool-\d{3}$' -action 'Workflow' -metadataPath 'repo-secrets-metadata.json'

      - name: Comprobar fecha y actualizar secrets de organizaci칩n
        shell: powershell
        run: .github/scripts/ghtokenrotation.ps1 -keyvaultname $vaultName -matchPattern '^gh-org-pool-\d{3}$' -action 'StorageAccountDelivery' -metadataPath 'org-secrets-metadata.json'

      - name: Comprobar fecha y actualizar secrets de entorno (clientes)
        shell: powershell
        run: |
          $token = gh auth token
          gh auth status
          Write-Host 'Son iguales con el workflow:' $env:GITHUB_TOKEN -like $env:WORKFLOWTOKEN
          Write-Host 'Son iguales con el auth:' ($env:GITHUB_TOKEN -like $token)
          Write-Host 'Son iguales prueba rara:' ($env:GITHUB_TOKEN -like '***')
          .github/scripts/ghtokenrotation.ps1 -keyvaultname $vaultName -matchPattern '^client.*_AUTHCONTEXT-pool-\d{3}$' -action 'environment' -metadataPath 'client-secrets-metadata.json'
        env:
          ENVJSON: ${{steps.DetermineDeploymentEnvironments.outputs.DeploymentEnvironmentsJson}}
          WORKFLOWTOKEN: ${{ fromJson(steps.ReadSecrets.outputs.Secrets).ghTokenWorkflow }}
          GITHUB_TOKEN: ${{github.token}}