name: Modify app.json
on: 
  workflow_dispatch:
    inputs:
      directCommit:
        description: 'Direct commit to the main branch'
        required: false
        default: 'false'
        type: boolean

jobs:
  ModifyAppJson:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Modify app.json files
        shell: powershell
        run: .github/modifyFiles.ps1

      - name: Commit and push changes
        if: ${{ github.event.inputs.directCommit == 'true' }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "Modify app.json files via workflow"
          git push origin HEAD:main
        shell: bash
