name: Modify app

on:
  workflow_dispatch: # Para pruebas manuales
  workflow_run:
    workflows: ["Create a new app"]
    types:
      - completed

jobs:

  ModifyApp:
    runs-on: windows-latest
    name: Modify app files
    outputs: 
      appName: ${{steps.ModifyAppJson.outputs.appName}}

    env:
      APPNAME: ${{steps.ModifyAppJson.outputs.appName}}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ matrix.branch }}
          token: ${{ secrets.ghTokenWorkflow }}
          fetch-depth: 0

      - name: Modify app.json files
        id: ModifyAppJson
        shell: powershell
        run: .github/scripts/modifyFiles.ps1 -Action "appjson"

      - name: Modify or add launch.json
        shell: powershell
        run: .github/scripts/modifyFiles.ps1 -Action "launch"
      
      - name: Modify or add settings.json
        shell: powershell
        run: .github/scripts/modifyFiles.ps1 -Action "settings"
      
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: debug
        run: |
          $userName = git config --get user.name
          Write-Host "---------------- $userName"
          $now = Get-Date
          $fechaString = $now.ToString("yyyyMMdd_HHmmss")
          $branch = "$fechaString" + "_$userName" +"_$env:APPNAME" 
          Write-Host "-------------- $branch"

      # - name: Commit changes y push a nueva rama
      #   shell: powershell
      #   run: |
      #     $now = Get-Date
      #     #yyyyMMdd_HHmm_BotGh
      #     $branch = "issue$env:APPNAME"
      #     git fetch origin
      #     $exists = (git ls-remote --heads origin $branch).Trim() -ne ""
      #     if (-not $exists) {
      #         git switch -c $branch
      #     } else {
      #         git switch $branch
      #     }
      #     git add .
      #     if (-not (git diff --cached --quiet)) {
      #         git commit -m "Establecer valores prederteminados de la app (app.json, settings y launch)"
      #     } else {
      #         Write-Host "No hay cambios para commitear."
      #     }
      #     git push origin $branch
      #   env: 
      #     APPNAME: ${{steps.ModifyAppJson.outputs.appName}}