name: Modify app.json

on:
  workflow_dispatch:
    inputs:
      includeBranches:
        description: 'Branches to include'
        required: false
        default: 'main'

  workflow_run:
    workflows: ["Create a new app"]
    types:
      - completed

jobs:
  ModifyAppJson:
    runs-on: windows-latest
    name: Modify app.json files

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
          token: ${{ secrets.ghTokenWorkflow }}

      - name: Modify app.json files
        shell: powershell
        run: .github/modifyFiles.ps1 

      - name: Commit changes
        shell: powershell
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          
          git add .
          
          if (!(git diff --cached --quiet)) {
            git commit -m "Actualizar datos por defecto de app.json"
          } else {
            Write-Host "No hay cambios para commitear"
          }

      - name: Push changes
        shell: powershell
        env:
          GH_TOKEN: ${{ secrets.ghTokenWorkflow }}
        run: |
          git push origin HEAD:${{ matrix.branch }}
