name: Modify app.json

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Create a new app"]
    types:
      - completed

jobs:
  Initialize:
    runs-on: windows-latest
    name: Initialize
    outputs:
      UpdateBranches: ${{ steps.GetBranches.outputs.Result }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

  ModifyAppJson:
    needs: Initialize
    runs-on: windows-latest
    name: Modify app.json files

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ matrix.branch }}
          token: ${{ secrets.ghTokenWorkflow }}

      - name: Modify app.json files
        shell: powershell
        run: .github/modifyFiles.ps1 
      
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit and push changes
        shell: powershell
        run: |
          git add .
          git commit -m "añadir datos por defecto de app.json"
          git push origin main
