name: Modify app.json
on: 
  workflow_dispatch:
    inputs:
      directCommit:
        description: 'Direct commit to the main branch'
        required: false
        default: 'false'
        type: boolean

jobs:
  ModifyAppJson:
    runs-on: [windows-latest]
    name: Modify app.json
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Modify app.json
        uses: .github\modifyFiles.ps1