name: Modify app.json
on: 
  workflow_dispatch:
    inputs:
      directCommit:
        description: 'Direct commit to the main branch'
        required: false
        default: 'false'
        type: boolean

jobs:
  ModifyAppJson:
    runs-on: [windows-latest]
    name: Modify app.json
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Modify app.json
        shell: powershell
        run: .github/modifyFiles.ps1
      
      - name: Commit and push changes
        if: ${{ github.event.inputs.directCommit == 'true' }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Modify app.json with GitHub Actions"
          git push origin HEAD:main