name: Modify app.json
on: 
  workflow_dispatch:
    inputs:
      directCommit:
        description: 'Direct commit to the main branch'
        required: false
        default: 'false'
        type: boolean

jobs:
  Initialize:
    runs-on: windows-latest
    name: Initialize
    outputs:
      UpdateBranches: ${{ steps.GetBranches.outputs.Result }}
      TemplateUrl: ${{ steps.DetermineTemplateUrl.outputs.TemplateUrl }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Read settings
        id: ReadSettings
        uses: microsoft/AL-Go-Actions/ReadSettings@v7.2
        with:
          shell: powershell
          get: templateUrl

      - name: Get Workflow Multi-Run Branches
        id: GetBranches
        uses: microsoft/AL-Go-Actions/GetWorkflowMultiRunBranches@v7.2
        with:
          shell: powershell
          includeBranches: ${{ github.event.inputs.includeBranches }}
  
  ModifyAppJson:
    needs: Initialize
    name: Modify app.json files
    runs-on: windows-latest
    strategy:
      matrix:
        branch: ${{ fromJson(needs.Initialize.outputs.UpdateBranches).branches }}
      fail-fast: false

    steps:
      - name: Dump Workflow Information
        uses: microsoft/AL-Go-Actions/DumpWorkflowInfo@v7.2
        with:
          shell: powershell

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ matrix.branch }}

      - name: Initialize the workflow
        id: init
        uses: microsoft/AL-Go-Actions/WorkflowInitialize@v7.2
        with:
          shell: powershell

      - name: Read settings
        uses: microsoft/AL-Go-Actions/ReadSettings@v7.2
        with:
          shell: powershell
          get: commitOptions

      - name: Read secrets
        id: ReadSecrets
        uses: microsoft/AL-Go-Actions/ReadSecrets@v7.2
        with:
          shell: powershell
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: 'ghTokenWorkflow'

      - name: Calculate Commit Options
        env:
          directCommit: '${{ github.event.inputs.directCommit }}'
          downloadLatest: '${{ github.event.inputs.downloadLatest }}'
        run: |
          $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
          if('${{ github.event_name }}' -eq 'workflow_dispatch') {
            Write-Host "Using inputs from workflow_dispatch event"
            $directCommit = $env:directCommit
            $downloadLatest = $env:downloadLatest
          }
          else {
            Write-Host "Using inputs from commitOptions setting"
            $commitOptions = $env:commitOptions | ConvertFrom-Json # Available from ReadSettings step
            $directCommit=$(-not $commitOptions.createPullRequest)
            $downloadLatest=$true
          }
          Add-Content -Encoding UTF8 -Path $env:GITHUB_ENV -Value "directCommit=$directCommit"
          Add-Content -Encoding UTF8 -Path $env:GITHUB_ENV -Value "downloadLatest=$downloadLatest"

      - name: Modify app.json files
        shell: powershell
        run: .github/modifyFiles.ps1

      - name: Finalize the workflow
        if: always()
        uses: microsoft/AL-Go-Actions/WorkflowPostProcess@v7.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          shell: powershell
          telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          currentJobContext: ${{ toJson(job) }}
