name: Modify app.json

on: 
  workflow_dispatch:
    inputs:
      directCommit:
        description: 'Direct commit to the main branch'
        required: false
        default: 'false'
        type: boolean

jobs:
  Initialize:
    runs-on: windows-latest
    name: Initialize
    outputs:
      UpdateBranches: ${{ steps.GetBranches.outputs.Result }}
      TemplateUrl: ${{ steps.ReadSettings.outputs.templateUrl }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read settings
        id: ReadSettings
        uses: microsoft/AL-Go-Actions/ReadSettings@v7.2
        with:
          shell: powershell
          get: templateUrl

      - name: Get Workflow Multi-Run Branches
        id: GetBranches
        uses: microsoft/AL-Go-Actions/GetWorkflowMultiRunBranches@v7.2
        with:
          shell: powershell
          includeBranches: ${{ github.event.inputs.includeBranches }}

      - name: Calculate Commit Options
        id: CalculateCommit
        env:
          directCommit: '${{ github.event.inputs.directCommit }}'
        run: |
          echo "directCommit=$env:directCommit" >> $GITHUB_OUTPUT


  ModifyAppJson:
    needs: Initialize
    name: Modify app.json files
    runs-on: windows-latest
    strategy:
      matrix:
        branch: ${{ fromJson(needs.Initialize.outputs.UpdateBranches).branches }}
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - name: Modify app.json files
        shell: powershell
        run: .github/modifyFiles.ps1

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git diff --cached --quiet
          git commit -m "Actualización automática de app.json"
        shell: powershell

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin HEAD:${{ matrix.branch }}
        shell: powershell
