name: Test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:    
      GH_TOKEN: ${{secrets.ghTokenWorkflow}}
      
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{secrets.ghTokenWorkflow}}

      - name: Obtener appName
        run: | 
          $appName= Split-Path ${{github.repository}} -Leaf
          $workspace = $env:GITHUB_WORKSPACE
          Write-Host "-------------- WORKSPACE: $workspace"
          Write-Host "-------------- NAME: $appName"
        
      - name: obtener info de la app
        shell: powershell
        run: |
          DownloadAndImportBcContainerHelper
          $prueba = Get-BcContainerAppInfo
          $prueba 
