name: Test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Obtener appName
        run: | 
          $appName= Split-Path ${{github.repository}} -Leaf
          $workspace = $env:GITHUB_WORKSPACE
          Write-Host "-------------- WORKSPACE: $workspace"
          Write-Host "-------------- NAME: $appName"
        
      - name: Run a multi-line script
        run: |
          $prueba = Get-BcContainerAppInfo
          $prueba 
