name: Test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Obtener appName
        run: | 
          $appName= Split-Path ${{github.repository}} -Leaf
          Write-Host "-------------- NAME: $appName"
        
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
