name: Update Tecon System Files

on:
  workflow_dispatch:
    inputs:
      templateUrl:
        description: 'URL of the template to use for updating system files default is https://github.com/investigacionPrac/Actions'
        required: false
        default: 'https://github.com/investigacionPrac/Actions'
  schedule:
    - cron: '0 2 * * *' 

jobs:
  CheckForUpdates:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ matrix.branch }}
          token: ${{ secrets.ghTokenWorkflow }}
          fetch-depth: 0

      - name: Update Tecon System Files
        shell: powershell
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          .\.github\UpdateFiles.ps1 `
            -templateUrl "https://github.com/investigacionPrac/Actions" `
            -branch "main" `
            -downloadLatest $true `
            -update "Y"
      
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit and push changes
        shell: powershell
        run: |
          git add .
          git commit -m "Actualizar archivos del sistema de TECON"
          git push origin main