name: Update Tecon System Files

on:
  workflow_dispatch:
    inputs:
      templateUrl:
        description: 'URL of the template to use for updating system files default is https://github.com/investigacionPrac/Actions'
        required: false
        default: 'https://github.com/investigacionPrac/Actions'
  schedule:
    - cron: '0 2 * * *' 

jobs:
  CheckForUpdates:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read secrets
        id: ReadSecrets
        uses: microsoft/AL-Go-Actions/ReadSecrets@v7.2
        with:
          shell: powershell
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: 'ghTokenWorkflow'

      - name: Update Tecon System Files
        run: |
          Write-Host "Updating Tecon System Files..."
          .\UpdateTeconSystemFiles.ps1 -templateUrl ${{ inputs.templateUrl }} -token ${{ fromJson(steps.ReadSecrets.outputs.Secrets).ghTokenWorkflow }} -downloadLatest $true -update 'Y'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        shell: powershell
