name: Update Tecon System Files

on:
  workflow_dispatch:
    inputs:
      templateUrl:
        description: 'URL of the template to use for updating system files default is https://github.com/investigacionPrac/Actions'
        required: false
        default: 'https://github.com/investigacionPrac/Actions'
  schedule:
    - cron: '0 2 * * *' 

jobs:
  CheckForUpdates:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Tecon System Files
        shell: powershell
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth login --with-token < $Env:GITHUB_TOKEN
          .\.github\UpdateFiles.ps1 `
            -templateUrl "https://github.com/investigacionPrac/Actions" `
            -branch "main" `
            -downloadLatest $true `
            -update "Y"