name: Update Tecon System Files

on:
  workflow_dispatch: # For manual testing
    inputs:
      templateUrl:
        description: Template Repository URL
        required: false
        default: 'https://github.com/investigacionPrac/Actions'
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read
  id-token: write

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}


jobs:
  UpdateTeconSystemFiles:
    runs-on: windows-latest
    name: Update Tecon System Files

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ matrix.branch }}
          token: ${{ secrets.ghTokenWorkflow }}
      
      - name: Calculate Commit Options
        env:
          directCommit: '${{ github.event.inputs.directCommit }}'
          downloadLatest: '${{ github.event.inputs.downloadLatest }}'
        run: |
          $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
          if('${{ github.event_name }}' -eq 'workflow_dispatch') {
            Write-Host "Using inputs from workflow_dispatch event"
            $directCommit = $env:directCommit
            $downloadLatest = $env:downloadLatest
          }
          else {
            Write-Host "Using inputs from commitOptions setting"
            $commitOptions = $env:commitOptions | ConvertFrom-Json # Available from ReadSettings step
            $directCommit=$(-not $commitOptions.createPullRequest)
            $downloadLatest=$true
          }
          Add-Content -Encoding UTF8 -Path $env:GITHUB_ENV -Value "directCommit=$directCommit"
          Add-Content -Encoding UTF8 -Path $env:GITHUB_ENV -Value "downloadLatest=$downloadLatest"
            
      - name: Update Tecon System Files
        shell: powershell
        run: .github/updateTeconSystemFiles.ps1

      - name: Finalize the workflow
        if: always()
        uses: microsoft/AL-Go-Actions/WorkflowPostProcess@v7.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          shell: powershell
          telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          currentJobContext: ${{ toJson(job) }}
        
