name: Update Tecon System Files

on:
  workflow_dispatch: # For manual testing
    inputs:
      templateUrl:
        description: Template Repository URL
        required: false
        default: 'https://github.com/investigacionPrac/Actions'
  push:
    branches:
      - main

jobs:
  UpdateTeconSystemFiles:
    runs-on: windows-latest
    name: Update Tecon System Files

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ matrix.branch }}
          token: ${{ secrets.ghTokenWorkflow }}
      
      - name: Update Tecon System Files
        shell: powershell
        run: .github/updateTeconSystemFiles.ps1
      
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Create branch
        run: |
          git checkout -b update-tecon-system-files-${{ github.run_number}}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.ghTokenWorkflow }}
          branch: update-tecon-system-files-${{ github.run_number }}
          title: "Update Tecon System Files"
          body: "This PR updates the Tecon system files with the latest changes."
          base: main
          commit-message: "Update Tecon system files"
          labels: "update, tecon, system-files"